# Composers OpenAPI

openapi: 3.0.0

info:
  title: WEB 420 RESTful APIs - OpenAPI 3.0
  version: 1.0.0

servers:
  - url: http://localhost:3000/api-docs/
paths:
  /composers:
    summary: returns a list of composer documents.
    get:
      tags:
        - Composers
      summary: returns a list of composer documents
      responses:
        "200":
          description: Composer documents
        "500":
          description: Server Exception
        "501":
          description: MongoDB Exception
    post:
      tags:
        - Composers
      summary: Creates a new composer object
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                firstName:
                  type: string
                lastName:
                  type: string
      responses:
        "200":
          description: User added
        "500":
          description: Server Exception
        "501":
          description: MongoDB Exception
  /composers/{id}:
    summary: returns a composer document
    get:
      tags:
        - Composers
      parameters:
        - name: id
          in: path
          description: The composerId requested by the user
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Composer document in JSON format
        "500":
          description: Server Exception
        "501":
          description: MongoDB Exception
