# Composers OpenAPI

openapi: "3.0.0"

info:
  title: WEB 420 RESTful APIs - OpenAPI 3.0
  version: 1.0.0

servers:
  - url: http://localhost:3000/api-docs/
paths:
  /composers:
    get:
      tags:
        - Composers
      description: API for returning a list of composer documents
      summary: returns a list of composer documents
      responses:
        "200":
          description: Composer documents
        "500":
          description: Server Exception
        "501":
          description: MongoDB Exception
    post:
      tags:
        - Composers
      description: API for adding a new composer document
      summary: Creates a new composer object
      requestBody:
        description: Composer information
        content:
          application/json:
            schema:
              required:
                - type
              properties:
                type:
                  type: string
      responses:
        "200":
          description: User added
        "500":
          description: Server Exception
        "501":
          description: MongoDB Exception
  /composers/{id}:
    get:
      tags:
        - Composers
      description: API for returning a composer document
      summary: returns a composer document
      parameters:
        - name: id
          in: path
          required: true
          description: Composer document Id
          schema:
            type: string
      responses:
        "200":
          description: Composer document in JSON format
        "500":
          description: Server Exception
        "501":
          description: MongoDB Exception
